// front-end/src/app/ip-config/ip-config.component.ts
import { Component } from '@angular/core';
import { CookieService } from 'ngx-cookie-service';
import { FormsModule } from '@angular/forms'; 

@Component({
  selector: 'app-ip-config',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './ip-config.component.html',
  styleUrl: './ip-config.component.css'
})
export class IpConfigComponent {
  ipAddress: string = '';

  constructor(private cookieService: CookieService) {}

  saveIpAddress() {
    this.cookieService.set('backendIp', this.ipAddress);
    window.location.href = '/';
  }
}

<div>
    <h2>Configurar Endereço IP do Back-end</h2>
    <input type="text" placeholder="Digite o IP do Back-end" [(ngModel)]="ipAddress">
    <button (click)="saveIpAddress()">Salvar</button>
  </div>

// front-end-react/src/components/ip-config/IpConfig.jsx
import React, { useState } from 'react';
import Cookies from 'js-cookie';
import "./style.css"

const IpConfig = () => {
  const [ipAddress, setIpAddress] = useState('');

  const saveIpAddress = () => {
    Cookies.set('backendIp', ipAddress);
    window.location.href = '/';
  };

  return (
    <div>
      <h2>Configurar Endereço IP do Back-end</h2>
      <input 
        type="text" 
        placeholder="Digite o IP do Back-end" 
        value={ipAddress} 
        onChange={(e) => setIpAddress(e.target.value)} 
      />
      <button onClick={saveIpAddress}>Salvar</button>
    </div>
  );
};

export default IpConfig;
